services:

  postgres:
    container_name: cas-order-pg
    image: postgres:17.0-alpine3.20
    volumes:
      - pg-order-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "${PG_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${PG_DB} -U ${PG_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5 
    restart: unless-stopped

  app:
    container_name: cas-order
    build: .
    volumes:
      - ./secrets:/secrets
    env_file:
      - .env
    ports:
      - "${HTTP_PORT}:8080"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  pg-order-data:

networks:
  cas-net:
    external: true